// <auto-generated />
namespace BACAgent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class update11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update11));
        
        string IMigrationMetadata.Id
        {
            get { return "202005260029368_update11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
